service: aws-lambda-http-graphql-1

useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-common-excludes

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    SUPER_SECRET_PASS: '☺♠◘•♣♠○♦☺♣♪'

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
